version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      timezone: "Europe/Prague"
    rebase-strategy: disabled
    labels:
      - "github actions"
      - "dependencies"
    open-pull-requests-limit: 5
    assignees:
      - "yasanglass"
