baseURL = "https://yasan.glass/"
languageCode = "en"
title = "Yasan Glass"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "RSS"]

[params]
  twitterCreator = "@yasan"
  defaultImage = "/card.png"
