name: Build

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.160.1"
          extended: true

      - name: Build Hugo Site
        run: hugo --minify
