name: Deploy

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Hugo Site to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.160.1"
          extended: true

      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v6

      - name: Build Hugo Site
        run: hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
